// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpcControllerClient.Models;

#nullable disable

namespace RpcControllerClient.Migrations
{
    [DbContext(typeof(RpcClientContext))]
    [Migration("20251125092353_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("RpcControllerClient.Models.Devices", b =>
                {
                    b.Property<int>("DevicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeviceStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("DevicesId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RpcControllerClient.Models.Pupils", b =>
                {
                    b.Property<int>("PupilsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CardValidityPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePupil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatronymicPupil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SurnamePupil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PupilsId");

                    b.ToTable("Pupils");
                });

            modelBuilder.Entity("RpcControllerClient.Models.Visiting", b =>
                {
                    b.Property<int>("VisitingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevicesId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VisitingDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitingId");

                    b.HasIndex("DevicesId");

                    b.ToTable("Visitings");
                });

            modelBuilder.Entity("VisitingPupils", b =>
                {
                    b.Property<int>("VisitingPupilsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PupilsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitingPupilsId");

                    b.HasIndex("PupilsId");

                    b.HasIndex("VisitingId");

                    b.ToTable("VisitingPupils");
                });

            modelBuilder.Entity("RpcControllerClient.Models.Visiting", b =>
                {
                    b.HasOne("RpcControllerClient.Models.Devices", "Devices")
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("VisitingPupils", b =>
                {
                    b.HasOne("RpcControllerClient.Models.Pupils", null)
                        .WithMany()
                        .HasForeignKey("PupilsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpcControllerClient.Models.Visiting", null)
                        .WithMany()
                        .HasForeignKey("VisitingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
