// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpcControllerClient.Models;

#nullable disable

namespace RpcControllerClient.Migrations
{
    [DbContext(typeof(RpcClientContext))]
    partial class RpcClientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("RpcControllerClient.Models.Devices", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeviceStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RpcControllerClient.Models.Pupils", b =>
                {
                    b.Property<int>("PupilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CardValidityPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePupil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatronymicPupil")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurnamePupil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PupilId");

                    b.ToTable("Pupils");
                });

            modelBuilder.Entity("RpcControllerClient.Models.Visiting", b =>
                {
                    b.Property<int>("VisitingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PupilId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VisitingDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitingId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PupilId");

                    b.ToTable("Visitings");
                });

            modelBuilder.Entity("RpcControllerClient.Models.Visiting", b =>
                {
                    b.HasOne("RpcControllerClient.Models.Devices", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpcControllerClient.Models.Pupils", "Pupil")
                        .WithMany()
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Pupil");
                });
#pragma warning restore 612, 618
        }
    }
}
